### ISSUE TITLE
Change /events route to /actions

### ISSUE THREAD

**Issue by ryanmdoyle** [code4sac/neighborhood-connect-api#39]
https://github.com/code4sac/neighborhood-connect-api/blob/b50f2748fc2de484490d30d4abe5f475935d9342/app.js#L23

Ok, I wasn't part of the backend conversations too much in the development of this, but it seems that this route referenced should be `app.use('/actions', actions);` instead of `app.use('/events', actions);`.  On the front end it's confusing to be referencing "actions" all the time, although the route for actions is named events.  It's my understanding that there will be multiple types of "actions" later on (such as events, announcements, etc) so I think it would work better to have the route /actions.  We are, after using actionsRouter and Actions model.

**Comment by spraguejdev** [comment]
That's a valid concern? I'm okay with changing okay route to /actions. Anyone else?

**Comment by edamron** [comment]
I think /actions is good.

**Comment by spraguejdev** [comment]
Change complete1
