### ISSUE TITLE
Do not reference the schema 'test' in SQL

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect-api#59]
Aside from connection configuration, we should not be referencing the schema name 'test' in any code.  The app probably only ever needs one schema, so it should be implicit.  This will allow better configuration later in case someone wants to use a 'prod' schema or other.

**Comment by josephmfaulkner** [comment]
I'll get right on this one. While I'm at it I'll populate the public schema with the migrations.

**Comment by josephmfaulkner** [comment]
@kelfink: I've got a PR open for this one.

**Comment by josephmfaulkner** [comment]
Just merged this to DEV
